### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by elifcevrim** [rvinas/HYFA#5]
I'm having trouble installing packages due to version conflicts. Can you suggest the right Python version for compatibility with the required packages?

**Comment by rvinas** [comment]
Hi Elif, thanks for your interest in our work. We were using Python 3.8.0 - can you install the packages using this version? If not, it would be nice if you could show the compatibility error.

**Comment by elifcevrim** [comment]
Thanks for your quick response. I'm currently facing an issue while installing the required packages. Here's the error I encountered:

```Collecting torch==1.8.0 (from -r requirements.txt (line 22))
  Using cached torch-1.8.0-cp38-cp38-manylinux1_x86_64.whl (735.5 MB)
Collecting torch-scatter==2.0.9 (from -r requirements.txt (line 23))
  Using cached torch_scatter-2.0.9.tar.gz (21 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i5657kpa/torch-scatter_035b5d25850b4a7eab3221ea047703d4/setup.py", line 8, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
```
How can I resolve this issue? I haven't found a solution yet. Could it possibly be related to the CUDA version?

**Comment by rvinas** [comment]
I see... Yes, this might be related to the CUDA version. In the past, I've also run into installation issues with torch-scatter. Perhaps you could try manually installing Pytorch first followed by torch-scatter?

According to the torch-scatter [documentation](https://pypi.org/project/torch-scatter/), if pytorch >= 1.8.0 is installed then you should be able to install torch-scatter as `conda install pytorch-scatter -c pyg` (or if you are using pip: `pip install torch-scatter -f https://data.pyg.org/whl/torch-1.8.0+${CUDA}.html`)
