### ISSUE TITLE
AssertionError when running "assert np.allclose(y_test_, y_test)"

### ISSUE THREAD

**Issue by Gongmian784** [rvinas/HYFA#7]
Hi, when running the codes of **compare to different baselines** in **evaluate_GTEx_v8_normalised.ipynb** using my own data, I found an AssertionError in line 142 a below:

> AssertionError                            Traceback (most recent call last)
Cell In[32], line 142
    140     y_test_pred = out['px_rate'].cpu().numpy()  # torch.distributions.normal.Normal(loc=out['px_rate'], scale=out['px_r']).mean.cpu().numpy()
    141     y_test_ = d.x_target.cpu().numpy()
--> 142 assert np.allclose(y_test_, y_test)
    144 sample_scores = score_fn(y_test, y_test_pred, sample_corr=sample_corr)
    146 # Append results
> 
> AssertionError: 

The target array of the aux_test_dataset is not consistent with the target array of the corresponding HypergraphDataset after we converted the aux_test_dataset into the HypergraphDataset.

After comparing d.target_dynamic['Participant ID'] and aux_test_dataset.adata_target.obs['Participant ID'], and also their expression arrays, I found the order of "Participand ID" and their expression data has changed. It seems that d.target_dynamic['Participant ID'] is ordered numerically and alphabetically instead of in the same order as aux_test_dataset.adata_target.obs['Participant ID']. For example:
`print(aux_test_dataset.adata_target.obs['Participant ID'].values)`
I got:
> ['GS12' 'GW133' 'GZ137' 'GW142' 'CT146' 'LBJ18' 'XQN39' 'SLG43' 'QG44' 'XQN75' 'ZGJ176' 'XN9063' 'PZ140']

After HypergraphDataset convertion and DataLoader:
`aux_test_dataset = HypergraphDataset(adata[test_mask], obs_source={'Tissue': source_tissues}, obs_target={'Tissue': [tt]})'`
`aux_test_loader = DataLoader(aux_test_dataset, batch_size=len(aux_test_dataset),collate_fn=collate_fn, shuffle=False)`
`d = next(iter(aux_test_loader))`
`print(d.target_dynamic['Participant ID'])`
The result changed into:
> ['CT146' 'GS12' 'GW133' 'GW142' 'GZ137' 'LBJ18' 'PZ140' 'QG44' 'SLG43' 'XN9063' 'XQN39' 'XQN75' 'ZGJ176']

The same is true of expression matrices (i.e. aux_test_dataset.adata_target.layers['x'].toarray() and d.x_target.cpu().numpy()).

How could I fix this error?

Thanks in advance!

Mian

**Comment by rvinas** [comment]
Thanks for raising this issue! Off the top of my head I don't know why this assert fails for your dataset. Could you perhaps try  sorting the data by `Participant ID` before passing it to `HypergraphDataset`?

**Comment by Gongmian784** [comment]
The error is fixed. Thanks a lot!
